version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: agalid
      POSTGRES_PASSWORD: agalid
      POSTGRES_DB: agalid
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: ../server
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    environment:
      DATABASE_URL: postgres://agalid:agalid@postgres:5432/agalid
      ALLOWED_ORIGIN: http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176
      PORT: 4001
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: info@agalid.com
      SMTP_PASS: ${GMAIL_PASS}
      EMAIL_FROM: info@agalid.com
      WHATSAPP_TOKEN: ${WHATSAPP_TOKEN}
      WHATSAPP_PHONE_ID: ${WHATSAPP_PHONE_ID}
      SEND_DELIVERY: "false"
    depends_on:
      - postgres
      - mailhog
    ports:
      - "4001:4001"
    volumes:
      - ../server:/app
      - /app/node_modules
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  pgdata:
